# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\Gym Managment System\Ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.groupBox = QtWidgets.QGroupBox(self.homePage)
        self.groupBox.setGeometry(QtCore.QRect(70, 110, 221, 281))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.homeCustomers = QtWidgets.QPushButton(self.groupBox)
        self.homeCustomers.setGeometry(QtCore.QRect(70, 60, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.homeCustomers.setFont(font)
        self.homeCustomers.setObjectName("homeCustomers")
        self.homeTrainers = QtWidgets.QPushButton(self.groupBox)
        self.homeTrainers.setGeometry(QtCore.QRect(70, 100, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.homeTrainers.setFont(font)
        self.homeTrainers.setObjectName("homeTrainers")
        self.homeGymHalls = QtWidgets.QPushButton(self.groupBox)
        self.homeGymHalls.setGeometry(QtCore.QRect(70, 140, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.homeGymHalls.setFont(font)
        self.homeGymHalls.setObjectName("homeGymHalls")
        self.homeEquipment = QtWidgets.QPushButton(self.groupBox)
        self.homeEquipment.setGeometry(QtCore.QRect(70, 180, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.homeEquipment.setFont(font)
        self.homeEquipment.setObjectName("homeEquipment")
        self.homeExercisePlans = QtWidgets.QPushButton(self.groupBox)
        self.homeExercisePlans.setGeometry(QtCore.QRect(70, 220, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.homeExercisePlans.setFont(font)
        self.homeExercisePlans.setObjectName("homeExercisePlans")
        self.label_4 = QtWidgets.QLabel(self.homePage)
        self.label_4.setGeometry(QtCore.QRect(380, 220, 41, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.homeSubscribe = QtWidgets.QPushButton(self.homePage)
        self.homeSubscribe.setGeometry(QtCore.QRect(480, 240, 171, 23))
        self.homeSubscribe.setObjectName("homeSubscribe")
        self.stackedWidget.addWidget(self.homePage)
        self.customerPage = QtWidgets.QWidget()
        self.customerPage.setObjectName("customerPage")
        self.customerGrid = QtWidgets.QListWidget(self.customerPage)
        self.customerGrid.setGeometry(QtCore.QRect(30, 70, 331, 361))
        self.customerGrid.setObjectName("customerGrid")
        self.label_5 = QtWidgets.QLabel(self.customerPage)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.deleteCustomerButton = QtWidgets.QPushButton(self.customerPage)
        self.deleteCustomerButton.setGeometry(QtCore.QRect(30, 440, 101, 23))
        self.deleteCustomerButton.setObjectName("deleteCustomerButton")
        self.label_8 = QtWidgets.QLabel(self.customerPage)
        self.label_8.setGeometry(QtCore.QRect(470, 70, 47, 13))
        self.label_8.setObjectName("label_8")
        self.customerNameEdit = QtWidgets.QLineEdit(self.customerPage)
        self.customerNameEdit.setGeometry(QtCore.QRect(540, 70, 113, 21))
        self.customerNameEdit.setObjectName("customerNameEdit")
        self.label_10 = QtWidgets.QLabel(self.customerPage)
        self.label_10.setGeometry(QtCore.QRect(470, 110, 47, 13))
        self.label_10.setObjectName("label_10")
        self.customerEmailEdit = QtWidgets.QLineEdit(self.customerPage)
        self.customerEmailEdit.setGeometry(QtCore.QRect(540, 110, 113, 20))
        self.customerEmailEdit.setObjectName("customerEmailEdit")
        self.createCustomerButton = QtWidgets.QPushButton(self.customerPage)
        self.createCustomerButton.setGeometry(QtCore.QRect(440, 150, 111, 23))
        self.createCustomerButton.setObjectName("createCustomerButton")
        self.updateCustomerButton = QtWidgets.QPushButton(self.customerPage)
        self.updateCustomerButton.setGeometry(QtCore.QRect(580, 150, 111, 23))
        self.updateCustomerButton.setObjectName("updateCustomerButton")
        self.subscriptionsGrid = QtWidgets.QListWidget(self.customerPage)
        self.subscriptionsGrid.setGeometry(QtCore.QRect(430, 260, 291, 171))
        self.subscriptionsGrid.setObjectName("subscriptionsGrid")
        self.label_9 = QtWidgets.QLabel(self.customerPage)
        self.label_9.setGeometry(QtCore.QRect(430, 190, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.cancelSubscriptionButton = QtWidgets.QPushButton(self.customerPage)
        self.cancelSubscriptionButton.setGeometry(QtCore.QRect(430, 440, 121, 21))
        self.cancelSubscriptionButton.setObjectName("cancelSubscriptionButton")
        self.customerBack = QtWidgets.QPushButton(self.customerPage)
        self.customerBack.setGeometry(QtCore.QRect(30, 510, 75, 23))
        self.customerBack.setObjectName("customerBack")
        self.stackedWidget.addWidget(self.customerPage)
        self.gymHallPage = QtWidgets.QWidget()
        self.gymHallPage.setObjectName("gymHallPage")
        self.gymHallGrid = QtWidgets.QListWidget(self.gymHallPage)
        self.gymHallGrid.setGeometry(QtCore.QRect(30, 70, 331, 361))
        self.gymHallGrid.setObjectName("gymHallGrid")
        self.label = QtWidgets.QLabel(self.gymHallPage)
        self.label.setGeometry(QtCore.QRect(30, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nameGymHallEdit = QtWidgets.QLineEdit(self.gymHallPage)
        self.nameGymHallEdit.setGeometry(QtCore.QRect(540, 200, 113, 21))
        self.nameGymHallEdit.setObjectName("nameGymHallEdit")
        self.label_12 = QtWidgets.QLabel(self.gymHallPage)
        self.label_12.setGeometry(QtCore.QRect(470, 200, 47, 13))
        self.label_12.setObjectName("label_12")
        self.createHallButton = QtWidgets.QPushButton(self.gymHallPage)
        self.createHallButton.setGeometry(QtCore.QRect(460, 250, 111, 23))
        self.createHallButton.setObjectName("createHallButton")
        self.deleteGymHallButton = QtWidgets.QPushButton(self.gymHallPage)
        self.deleteGymHallButton.setGeometry(QtCore.QRect(30, 440, 101, 21))
        self.deleteGymHallButton.setObjectName("deleteGymHallButton")
        self.updateGymHall = QtWidgets.QPushButton(self.gymHallPage)
        self.updateGymHall.setGeometry(QtCore.QRect(590, 250, 111, 23))
        self.updateGymHall.setObjectName("updateGymHall")
        self.gymHallBack = QtWidgets.QPushButton(self.gymHallPage)
        self.gymHallBack.setGeometry(QtCore.QRect(30, 520, 75, 23))
        self.gymHallBack.setObjectName("gymHallBack")
        self.stackedWidget.addWidget(self.gymHallPage)
        self.equipmentsPage = QtWidgets.QWidget()
        self.equipmentsPage.setObjectName("equipmentsPage")
        self.equipmentsGrid = QtWidgets.QListWidget(self.equipmentsPage)
        self.equipmentsGrid.setGeometry(QtCore.QRect(30, 70, 331, 361))
        self.equipmentsGrid.setObjectName("equipmentsGrid")
        self.nameEquipmentsEdit = QtWidgets.QLineEdit(self.equipmentsPage)
        self.nameEquipmentsEdit.setGeometry(QtCore.QRect(550, 110, 113, 21))
        self.nameEquipmentsEdit.setObjectName("nameEquipmentsEdit")
        self.label_14 = QtWidgets.QLabel(self.equipmentsPage)
        self.label_14.setGeometry(QtCore.QRect(480, 110, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.equipmentsPage)
        self.label_16.setGeometry(QtCore.QRect(30, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.createEquipmentButton = QtWidgets.QPushButton(self.equipmentsPage)
        self.createEquipmentButton.setGeometry(QtCore.QRect(470, 210, 111, 23))
        self.createEquipmentButton.setObjectName("createEquipmentButton")
        self.deleteEquipmentsButton = QtWidgets.QPushButton(self.equipmentsPage)
        self.deleteEquipmentsButton.setGeometry(QtCore.QRect(30, 440, 101, 21))
        self.deleteEquipmentsButton.setObjectName("deleteEquipmentsButton")
        self.updateEquipmentButton = QtWidgets.QPushButton(self.equipmentsPage)
        self.updateEquipmentButton.setGeometry(QtCore.QRect(600, 210, 111, 23))
        self.updateEquipmentButton.setObjectName("updateEquipmentButton")
        self.equipmentsGymHallComboBox = QtWidgets.QComboBox(self.equipmentsPage)
        self.equipmentsGymHallComboBox.setGeometry(QtCore.QRect(550, 150, 111, 22))
        self.equipmentsGymHallComboBox.setObjectName("equipmentsGymHallComboBox")
        self.label_18 = QtWidgets.QLabel(self.equipmentsPage)
        self.label_18.setGeometry(QtCore.QRect(480, 150, 47, 13))
        self.label_18.setObjectName("label_18")
        self.equipmentsBack = QtWidgets.QPushButton(self.equipmentsPage)
        self.equipmentsBack.setGeometry(QtCore.QRect(30, 520, 75, 23))
        self.equipmentsBack.setObjectName("equipmentsBack")
        self.stackedWidget.addWidget(self.equipmentsPage)
        self.trainersPage = QtWidgets.QWidget()
        self.trainersPage.setObjectName("trainersPage")
        self.label_15 = QtWidgets.QLabel(self.trainersPage)
        self.label_15.setGeometry(QtCore.QRect(470, 170, 47, 21))
        self.label_15.setObjectName("label_15")
        self.trainersGrid = QtWidgets.QListWidget(self.trainersPage)
        self.trainersGrid.setGeometry(QtCore.QRect(30, 70, 331, 361))
        self.trainersGrid.setObjectName("trainersGrid")
        self.createTrainerButton = QtWidgets.QPushButton(self.trainersPage)
        self.createTrainerButton.setGeometry(QtCore.QRect(470, 330, 81, 23))
        self.createTrainerButton.setObjectName("createTrainerButton")
        self.updateTrainerButton = QtWidgets.QPushButton(self.trainersPage)
        self.updateTrainerButton.setGeometry(QtCore.QRect(570, 330, 81, 23))
        self.updateTrainerButton.setObjectName("updateTrainerButton")
        self.nameTrainersEdit = QtWidgets.QLineEdit(self.trainersPage)
        self.nameTrainersEdit.setGeometry(QtCore.QRect(540, 170, 113, 21))
        self.nameTrainersEdit.setObjectName("nameTrainersEdit")
        self.label_17 = QtWidgets.QLabel(self.trainersPage)
        self.label_17.setGeometry(QtCore.QRect(30, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.deleteTrainersButton = QtWidgets.QPushButton(self.trainersPage)
        self.deleteTrainersButton.setGeometry(QtCore.QRect(30, 440, 101, 21))
        self.deleteTrainersButton.setObjectName("deleteTrainersButton")
        self.trainersGymHallComboBox = QtWidgets.QComboBox(self.trainersPage)
        self.trainersGymHallComboBox.setGeometry(QtCore.QRect(540, 210, 111, 22))
        self.trainersGymHallComboBox.setObjectName("trainersGymHallComboBox")
        self.label_11 = QtWidgets.QLabel(self.trainersPage)
        self.label_11.setGeometry(QtCore.QRect(470, 210, 47, 21))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.trainersPage)
        self.label_13.setGeometry(QtCore.QRect(470, 250, 61, 21))
        self.label_13.setObjectName("label_13")
        self.trainerWorkStart = QtWidgets.QSpinBox(self.trainersPage)
        self.trainerWorkStart.setGeometry(QtCore.QRect(540, 250, 111, 22))
        self.trainerWorkStart.setObjectName("trainerWorkStart")
        self.label_19 = QtWidgets.QLabel(self.trainersPage)
        self.label_19.setGeometry(QtCore.QRect(470, 290, 61, 21))
        self.label_19.setObjectName("label_19")
        self.trainerWorkEnd = QtWidgets.QSpinBox(self.trainersPage)
        self.trainerWorkEnd.setGeometry(QtCore.QRect(540, 290, 111, 22))
        self.trainerWorkEnd.setObjectName("trainerWorkEnd")
        self.trainersBack = QtWidgets.QPushButton(self.trainersPage)
        self.trainersBack.setGeometry(QtCore.QRect(30, 520, 75, 23))
        self.trainersBack.setObjectName("trainersBack")
        self.stackedWidget.addWidget(self.trainersPage)
        self.exercisePlanPage = QtWidgets.QWidget()
        self.exercisePlanPage.setObjectName("exercisePlanPage")
        self.label_20 = QtWidgets.QLabel(self.exercisePlanPage)
        self.label_20.setGeometry(QtCore.QRect(300, 50, 47, 21))
        self.label_20.setObjectName("label_20")
        self.exercisePlanTrainerComboBox = QtWidgets.QComboBox(self.exercisePlanPage)
        self.exercisePlanTrainerComboBox.setGeometry(QtCore.QRect(360, 50, 111, 22))
        self.exercisePlanTrainerComboBox.setObjectName("exercisePlanTrainerComboBox")
        self.label_21 = QtWidgets.QLabel(self.exercisePlanPage)
        self.label_21.setGeometry(QtCore.QRect(300, 90, 47, 21))
        self.label_21.setObjectName("label_21")
        self.exercisePlanComboBox = QtWidgets.QComboBox(self.exercisePlanPage)
        self.exercisePlanComboBox.setGeometry(QtCore.QRect(360, 90, 111, 22))
        self.exercisePlanComboBox.setObjectName("exercisePlanComboBox")
        self.exercisePlanItems = QtWidgets.QListWidget(self.exercisePlanPage)
        self.exercisePlanItems.setGeometry(QtCore.QRect(15, 190, 281, 311))
        self.exercisePlanItems.setObjectName("exercisePlanItems")
        self.label_22 = QtWidgets.QLabel(self.exercisePlanPage)
        self.label_22.setGeometry(QtCore.QRect(16, 150, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.exercisePlanPage)
        self.label_23.setGeometry(QtCore.QRect(440, 190, 61, 21))
        self.label_23.setObjectName("label_23")
        self.execerisePlanEquipmentComboBox = QtWidgets.QComboBox(self.exercisePlanPage)
        self.execerisePlanEquipmentComboBox.setGeometry(QtCore.QRect(530, 190, 131, 22))
        self.execerisePlanEquipmentComboBox.setObjectName("execerisePlanEquipmentComboBox")
        self.label_24 = QtWidgets.QLabel(self.exercisePlanPage)
        self.label_24.setGeometry(QtCore.QRect(440, 250, 47, 21))
        self.label_24.setObjectName("label_24")
        self.exercisePlanDuration = QtWidgets.QSpinBox(self.exercisePlanPage)
        self.exercisePlanDuration.setGeometry(QtCore.QRect(530, 250, 131, 22))
        self.exercisePlanDuration.setObjectName("exercisePlanDuration")
        self.label_25 = QtWidgets.QLabel(self.exercisePlanPage)
        self.label_25.setGeometry(QtCore.QRect(440, 310, 47, 13))
        self.label_25.setObjectName("label_25")
        self.exercisePlanSteps = QtWidgets.QTextEdit(self.exercisePlanPage)
        self.exercisePlanSteps.setGeometry(QtCore.QRect(530, 310, 131, 151))
        self.exercisePlanSteps.setObjectName("exercisePlanSteps")
        self.createExercisePlanButton = QtWidgets.QPushButton(self.exercisePlanPage)
        self.createExercisePlanButton.setGeometry(QtCore.QRect(360, 480, 151, 23))
        self.createExercisePlanButton.setObjectName("createExercisePlanButton")
        self.updateExercisePlanButton = QtWidgets.QPushButton(self.exercisePlanPage)
        self.updateExercisePlanButton.setGeometry(QtCore.QRect(610, 480, 151, 23))
        self.updateExercisePlanButton.setObjectName("updateExercisePlanButton")
        self.label_26 = QtWidgets.QLabel(self.exercisePlanPage)
        self.label_26.setGeometry(QtCore.QRect(10, 0, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.exercisePlanBack = QtWidgets.QPushButton(self.exercisePlanPage)
        self.exercisePlanBack.setGeometry(QtCore.QRect(20, 520, 75, 23))
        self.exercisePlanBack.setObjectName("exercisePlanBack")
        self.stackedWidget.addWidget(self.exercisePlanPage)
        self.subscribePage = QtWidgets.QWidget()
        self.subscribePage.setObjectName("subscribePage")
        self.label_2 = QtWidgets.QLabel(self.subscribePage)
        self.label_2.setGeometry(QtCore.QRect(290, 160, 47, 21))
        self.label_2.setObjectName("label_2")
        self.subscribeGymHallComboBox = QtWidgets.QComboBox(self.subscribePage)
        self.subscribeGymHallComboBox.setGeometry(QtCore.QRect(360, 160, 121, 22))
        self.subscribeGymHallComboBox.setObjectName("subscribeGymHallComboBox")
        self.subscribeTrainerComboBox = QtWidgets.QComboBox(self.subscribePage)
        self.subscribeTrainerComboBox.setGeometry(QtCore.QRect(360, 200, 121, 22))
        self.subscribeTrainerComboBox.setObjectName("subscribeTrainerComboBox")
        self.label_3 = QtWidgets.QLabel(self.subscribePage)
        self.label_3.setGeometry(QtCore.QRect(290, 200, 47, 21))
        self.label_3.setObjectName("label_3")
        self.subscribeExercisePlanComboBox = QtWidgets.QComboBox(self.subscribePage)
        self.subscribeExercisePlanComboBox.setGeometry(QtCore.QRect(360, 240, 121, 22))
        self.subscribeExercisePlanComboBox.setObjectName("subscribeExercisePlanComboBox")
        self.label_6 = QtWidgets.QLabel(self.subscribePage)
        self.label_6.setGeometry(QtCore.QRect(290, 240, 71, 21))
        self.label_6.setObjectName("label_6")
        self.subscribeDailyStart = QtWidgets.QTimeEdit(self.subscribePage)
        self.subscribeDailyStart.setGeometry(QtCore.QRect(360, 280, 121, 22))
        self.subscribeDailyStart.setObjectName("subscribeDailyStart")
        self.label_7 = QtWidgets.QLabel(self.subscribePage)
        self.label_7.setGeometry(QtCore.QRect(290, 280, 61, 21))
        self.label_7.setObjectName("label_7")
        self.subscribeDailyEnd = QtWidgets.QTimeEdit(self.subscribePage)
        self.subscribeDailyEnd.setGeometry(QtCore.QRect(360, 320, 121, 22))
        self.subscribeDailyEnd.setObjectName("subscribeDailyEnd")
        self.label_27 = QtWidgets.QLabel(self.subscribePage)
        self.label_27.setGeometry(QtCore.QRect(290, 320, 61, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.subscribePage)
        self.label_28.setGeometry(QtCore.QRect(290, 120, 47, 21))
        self.label_28.setObjectName("label_28")
        self.subscribeCustomerComboBox = QtWidgets.QComboBox(self.subscribePage)
        self.subscribeCustomerComboBox.setGeometry(QtCore.QRect(360, 120, 121, 22))
        self.subscribeCustomerComboBox.setObjectName("subscribeCustomerComboBox")
        self.subcribeButton = QtWidgets.QPushButton(self.subscribePage)
        self.subcribeButton.setGeometry(QtCore.QRect(290, 370, 61, 23))
        self.subcribeButton.setObjectName("subcribeButton")
        self.checkAvailabilityButton = QtWidgets.QPushButton(self.subscribePage)
        self.checkAvailabilityButton.setGeometry(QtCore.QRect(380, 370, 101, 23))
        self.checkAvailabilityButton.setObjectName("checkAvailabilityButton")
        self.label_29 = QtWidgets.QLabel(self.subscribePage)
        self.label_29.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.subscibeBack = QtWidgets.QPushButton(self.subscribePage)
        self.subscibeBack.setGeometry(QtCore.QRect(10, 520, 75, 23))
        self.subscibeBack.setObjectName("subscibeBack")
        self.stackedWidget.addWidget(self.subscribePage)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Manage"))
        self.homeCustomers.setText(_translate("MainWindow", "Customers"))
        self.homeTrainers.setText(_translate("MainWindow", "Trainers"))
        self.homeGymHalls.setText(_translate("MainWindow", "Gym Halls"))
        self.homeEquipment.setText(_translate("MainWindow", "Equipments"))
        self.homeExercisePlans.setText(_translate("MainWindow", "Exercise Plans"))
        self.label_4.setText(_translate("MainWindow", "Or"))
        self.homeSubscribe.setText(_translate("MainWindow", "Subcribe a customer to a plan"))
        self.label_5.setText(_translate("MainWindow", "Customer:"))
        self.deleteCustomerButton.setText(_translate("MainWindow", "Delete Customer"))
        self.label_8.setText(_translate("MainWindow", "Name"))
        self.label_10.setText(_translate("MainWindow", "Email"))
        self.createCustomerButton.setText(_translate("MainWindow", "Create Customer"))
        self.updateCustomerButton.setText(_translate("MainWindow", "Update Customer"))
        self.label_9.setText(_translate("MainWindow", "Subscriptions:"))
        self.cancelSubscriptionButton.setText(_translate("MainWindow", "Cancel Subscription"))
        self.customerBack.setText(_translate("MainWindow", "Back"))
        self.label.setText(_translate("MainWindow", "Gym Hall:"))
        self.label_12.setText(_translate("MainWindow", "Name"))
        self.createHallButton.setText(_translate("MainWindow", "Create Hall"))
        self.deleteGymHallButton.setText(_translate("MainWindow", "Delete Gym Hall"))
        self.updateGymHall.setText(_translate("MainWindow", "Update Hall"))
        self.gymHallBack.setText(_translate("MainWindow", "Back"))
        self.label_14.setText(_translate("MainWindow", "Name"))
        self.label_16.setText(_translate("MainWindow", "Equipments:"))
        self.createEquipmentButton.setText(_translate("MainWindow", "Create Equipment"))
        self.deleteEquipmentsButton.setText(_translate("MainWindow", "Delete Equipment"))
        self.updateEquipmentButton.setText(_translate("MainWindow", "Update Equipment"))
        self.label_18.setText(_translate("MainWindow", "Gym Hall"))
        self.equipmentsBack.setText(_translate("MainWindow", "Back"))
        self.label_15.setText(_translate("MainWindow", "Name"))
        self.createTrainerButton.setText(_translate("MainWindow", "Create Trainer"))
        self.updateTrainerButton.setText(_translate("MainWindow", "Update Trainer"))
        self.label_17.setText(_translate("MainWindow", "Trainers:"))
        self.deleteTrainersButton.setText(_translate("MainWindow", "Delete Trainer"))
        self.label_11.setText(_translate("MainWindow", "Gym Hall"))
        self.label_13.setText(_translate("MainWindow", "Work Start"))
        self.label_19.setText(_translate("MainWindow", "Work End"))
        self.trainersBack.setText(_translate("MainWindow", "Back"))
        self.label_20.setText(_translate("MainWindow", "Trainer"))
        self.label_21.setText(_translate("MainWindow", "Plan"))
        self.label_22.setText(_translate("MainWindow", "Plan Items"))
        self.label_23.setText(_translate("MainWindow", "Equipment"))
        self.label_24.setText(_translate("MainWindow", "Duration"))
        self.label_25.setText(_translate("MainWindow", "Steps"))
        self.createExercisePlanButton.setText(_translate("MainWindow", "Create Exercise Plan"))
        self.updateExercisePlanButton.setText(_translate("MainWindow", "Update Exercise Plan"))
        self.label_26.setText(_translate("MainWindow", "Exercise Plan:"))
        self.exercisePlanBack.setText(_translate("MainWindow", "Back"))
        self.label_2.setText(_translate("MainWindow", "Gym Hall"))
        self.label_3.setText(_translate("MainWindow", "Trainer"))
        self.label_6.setText(_translate("MainWindow", "Exercise Plan"))
        self.label_7.setText(_translate("MainWindow", "Daily Start"))
        self.label_27.setText(_translate("MainWindow", "Daily End"))
        self.label_28.setText(_translate("MainWindow", "Customer"))
        self.subcribeButton.setText(_translate("MainWindow", "Subscirbe"))
        self.checkAvailabilityButton.setText(_translate("MainWindow", "Check Availability"))
        self.label_29.setText(_translate("MainWindow", "Subscribe:"))
        self.subscibeBack.setText(_translate("MainWindow", "Back"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

