# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\Gym Managment System\Ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 607)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setObjectName("stackedWidget")
        self.hallChoicePage = QtWidgets.QWidget()
        self.hallChoicePage.setObjectName("hallChoicePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.hallChoicePage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.hallChoicePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.listWidget = QtWidgets.QListWidget(self.hallChoicePage)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.createHallButton = QtWidgets.QPushButton(self.hallChoicePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createHallButton.sizePolicy().hasHeightForWidth())
        self.createHallButton.setSizePolicy(sizePolicy)
        self.createHallButton.setObjectName("createHallButton")
        self.horizontalLayout.addWidget(self.createHallButton)
        self.label_2 = QtWidgets.QLabel(self.hallChoicePage)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.chooseHallButton = QtWidgets.QPushButton(self.hallChoicePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseHallButton.sizePolicy().hasHeightForWidth())
        self.chooseHallButton.setSizePolicy(sizePolicy)
        self.chooseHallButton.setObjectName("chooseHallButton")
        self.horizontalLayout.addWidget(self.chooseHallButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.hallChoicePage)
        self.createHallPage = QtWidgets.QWidget()
        self.createHallPage.setObjectName("createHallPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.createHallPage)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.createHallPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(100, -1, 100, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.createHallPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.createHallLineEdit = QtWidgets.QLineEdit(self.createHallPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createHallLineEdit.sizePolicy().hasHeightForWidth())
        self.createHallLineEdit.setSizePolicy(sizePolicy)
        self.createHallLineEdit.setObjectName("createHallLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.createHallLineEdit)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.createHallBackButton = QtWidgets.QPushButton(self.createHallPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createHallBackButton.sizePolicy().hasHeightForWidth())
        self.createHallBackButton.setSizePolicy(sizePolicy)
        self.createHallBackButton.setObjectName("createHallBackButton")
        self.horizontalLayout_2.addWidget(self.createHallBackButton, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.finalCreateHallButton = QtWidgets.QPushButton(self.createHallPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finalCreateHallButton.sizePolicy().hasHeightForWidth())
        self.finalCreateHallButton.setSizePolicy(sizePolicy)
        self.finalCreateHallButton.setObjectName("finalCreateHallButton")
        self.horizontalLayout_2.addWidget(self.finalCreateHallButton, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.createHallPage)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose a gym hall,"))
        self.createHallButton.setText(_translate("MainWindow", "Create Hall"))
        self.label_2.setText(_translate("MainWindow", "Or"))
        self.chooseHallButton.setText(_translate("MainWindow", "Choose Hall"))
        self.label_3.setText(_translate("MainWindow", "Create gym hall,"))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.createHallBackButton.setText(_translate("MainWindow", "Back"))
        self.finalCreateHallButton.setText(_translate("MainWindow", "Create Hall"))

